### ISSUE TITLE
Final image maybe too big?

### ISSUE THREAD

**Issue by deanmaniatis** [axw/juju-lxd-centos-image-builder#1]
The resulting image is around 515MB and it made me wonder why is to so big when the default centos7 image from linuxcontainers.org it's just 65MB. I manually launched a default centos/7 and installed the same packages as your script, published it locally and it was around 168MB. Is it possible that the image gains "weight" during export and re-import ?

**Comment by axw** [comment]
@deanmaniatis Thanks for reporting the issue, I had not noticed that.

This is because the image is not being compressed in the final step. I've pushed a fix for that, which gets it down to ~175MB. It's bigger because a bunch of additional RPMs are installed.
